#pragma once
#include "CoreMinimal.h"
DECLARE_LOG_CATEGORY_EXTERN(LogWTGQuest, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogWTGAI, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogWTGPuzzle, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogWTGWorld, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogWTGSave, Log, All);
DECLARE_LOG_CATEGORY_EXTERN(LogWTGInventory, Log, All);
