#include "Core/WTGLog.h"
DEFINE_LOG_CATEGORY(LogWTGQuest);
DEFINE_LOG_CATEGORY(LogWTGAI);
DEFINE_LOG_CATEGORY(LogWTGPuzzle);
DEFINE_LOG_CATEGORY(LogWTGWorld);
DEFINE_LOG_CATEGORY(LogWTGSave);
DEFINE_LOG_CATEGORY(LogWTGInventory);
