"""Validated world profiles -> portable definitions. No per-district code generation."""
import json,argparse,math,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
SCHEMAS={
'NPC':('npc','NPCs',[('s','id'),('s','name'),('s','faction'),('s','role'),('s','dialogue'),('vf','position'),('vf','hours'),('vvf','destinations')]),
'District':('districts','Districts',[('s','id'),('s','name'),('vf','bounds'),('f','threat'),('s','ambient'),('f','light'),('vs','tags'),('vs','activities'),('vs','events'),('vs','safehouses'),('vs','enemies')]),
'Guard':('guards','Guards',[('s','id'),('s','profile'),('s','faction'),('s','district'),('vf','position'),('vvf','patrol'),('vs','requires'),('vs','tags')]+[('f',x) for x in ['sight','hearing','walk','chase','health','radio_delay','radio_range','full_range','simple_range']]),
'Location':('locations','Locations',[('s','id'),('s','name'),('vf','position'),('f','radius'),('s','action'),('b','safehouse')]),
'WorldEvent':('events','WorldEvents',[('s','id'),('s','name'),('s','type'),('s','district'),('vf','position')]+[('f',x) for x in ['chance','min_heat','max_heat','start_hour','end_hour']]+[('vs',x) for x in ['weathers','requires','require_tags']]+[('f','cooldown'),('b','hostile'),('s','action'),('f','noise'),('f','heat')]),
'Hide':('hides','Hides',[('s','id'),('s','name'),('vf','position'),('vf','exit'),('f','radius')]),
'CCTV':('cameras','Cameras',[('s','id'),('vf','position'),('vf','rotation'),('f','radius'),('s','disabled_tag'),('s','power_tag'),('f','alarm_heat')]),
'Weather':('weather','WeatherProfiles',[('s','id'),('f','visibility'),('f','noise'),('f','fog')]),
'Faction':('factions','Factions',[('s','a'),('s','b'),('s','relation')]),
'Message':('messages','Messages',[('s','id'),('s','sender'),('s','text'),('vs','requires'),('vs','tags'),('f','min_heat')]),
'PhoneApp':('phone_apps','PhoneApps',[('s','id'),('s','title'),('s','text'),('vs','on_open')]),
'Noise':('noise','NoiseProfiles',[('s','id'),('f','radius'),('f','intensity'),('f','heat')]),
'Combination':('combinations','Combinations',[('s','id'),('s','title'),('vs','evidence'),('s','action')])}
TYPES={'s':'std::string','vs':'std::vector<std::string>','vf':'std::vector<double>','vvf':'std::vector<std::vector<double>>','f':'double','b':'bool'}
def validate(w,c):
 ids={a['id'] for a in c['actions']}; evidence={a['evidence'] for a in c['actions'] if a['evidence']}; districts={a['id'] for a in w['districts']}
 for _,(table,_,fields) in SCHEMAS.items():
  seen=set()
  for row in w[table]:
   if 'id' in row:
    if row['id'] in seen:raise ValueError('Duplicate '+table+' ID')
    seen.add(row['id'])
   for typ,key in fields:
    val=row[key]
    if typ=='f' and (not isinstance(val,(float,int)) or not math.isfinite(val)):raise ValueError('Invalid number')
    if typ=='vf' and (not isinstance(val,list) or not all(isinstance(x,(float,int)) and math.isfinite(x) for x in val)):raise ValueError('Invalid vector')
   if 'position' in row and len(row['position'])!=3:raise ValueError('Position size')
   if 'district' in row and row['district'] not in districts:raise ValueError('Unknown district')
   if 'requires' in row and not set(row['requires'])<=ids:raise ValueError('Unknown prerequisites')
   if row.get('action') and row['action'] not in ids:raise ValueError('Unknown action')
 for d in w['districts']:
  if len(d['bounds'])!=6 or any(d['bounds'][i]>=d['bounds'][i+3] for i in range(3)):raise ValueError('Invalid district bounds')
 for e in w['events']:
  if not 0<=e['chance']<=1 or e['cooldown']<1 or not 0<=e['min_heat']<=e['max_heat']<=100:raise ValueError('Invalid event limits')
 for combo in w['combinations']:
  if not set(combo['evidence'])<=evidence:raise ValueError('Unknown combination evidence')
 for g in w['guards']:
  if not g['patrol'] or any(len(v)!=3 for v in g['patrol']) or g['full_range']<=0 or g['simple_range']<g['full_range']:raise ValueError('Invalid patrol')
 for loc in w['locations']:
  if loc['radius']<=0:raise ValueError('Invalid discovery radius')
 for cam in w['cameras']:
  if len(cam['rotation'])!=3 or cam['radius']<=0:raise ValueError('Invalid camera')
def generate(w,c):
 validate(w,c)
 def val(v):
  if isinstance(v,str):return json.dumps(v,ensure_ascii=False)
  if isinstance(v,bool):return 'true' if v else 'false'
  if isinstance(v,list):return '{'+','.join(map(val,v))+'}'
  return str(v)
 lines=['// Generated by Scripts/compile_world.py; edit Data/openworld.json.','#pragma once','#include <string>','#include <vector>','namespace Wroclaw {']
 for name,(table,fn,fields) in SCHEMAS.items():
  lines+=['struct '+name+'Def {'+';'.join(TYPES[t]+' '+('prerequisites' if k=='requires' else k) for t,k in fields)+';};','inline const std::vector<'+name+'Def>& '+fn+'(){static const std::vector<'+name+'Def> data={']
  for row in w[table]:lines+=['{'+','.join(val(row[key]) for _,key in fields)+'},']
  lines+=['};return data;}']
 for key in ['clock_rate','initial_hour','quiet_seconds','event_interval','heat_decay']:lines+=['inline constexpr double '+key+'='+val(w[key])+';']
 lines+=['inline const std::string initial_weather='+val(w['initial_weather'])+';','}']
 return '\n'.join(lines)+'\n'
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
 world_source=Path(os.environ.get('WTG_WORLD_INPUT',ROOT/'Data/openworld.json'))
 chapter_source=Path(os.environ.get('WTG_CHAPTER_INPUT',ROOT/'Data/chapter1.json'))
 text=generate(json.loads(world_source.read_text(encoding='utf-8')),json.loads(chapter_source.read_text(encoding='utf-8')));p=ROOT/'Source/WroclawTheGame/Content/WorldCatalog.h'
 if args.check:
  if not p.exists() or p.read_text()!=text:raise SystemExit('WorldCatalog.h is stale')
 else:p.write_text(text,encoding='utf-8')
