"""Validate gameplay data and emit the portable catalog shared by Unreal and tests."""
import argparse,json,math,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def compile_catalog(data):
    actions=data['actions']; ids=[a['id'] for a in actions]; idset=set(ids)
    if len(ids)!=len(idset): raise ValueError('Duplicate action ID')
    allowed={'read','pickup','virtual','use','code','password','door','choice','symbols','sequence','zone','lights','order','wires'}
    if not data['variants'] or len(set(data['variants']))!=len(data['variants']) or any(len(v)!=4 or set(v)!=set('1234') for v in data['variants']):raise ValueError('Light variants must be unique permutations of 1234')
    itemids={i['id'] for i in data['items']}
    if len(itemids)!=len(data['items']):raise ValueError('Duplicate item')
    for item in data['items']:
        if not 1<=item['stack']<=1000 or not 0<=item['weight']<=100:raise ValueError('Invalid item limits')
    for a in actions:
        if not re.fullmatch(r'[a-z0-9_]+',a['id']):raise ValueError('Invalid stable ID')
        if a['kind'] not in allowed:raise ValueError('Unknown interaction kind')
        if a['alternate'] and a['alternate'] not in idset:raise ValueError('Unknown alternative')
        if a['answer'] and a['answer']!='@variant' and not 1<=len(a['answer'])<=8:raise ValueError('Unsupported answer length')
        for k in ('requires','clues','any_of'):
            if not set(a[k])<=idset:raise ValueError(f"Unknown references: {a['id']}/{k}")
        for k in ('items','reward','consume'):
            if not set(a[k])<=itemids:raise ValueError('Unknown item')
        if len(a['position'])!=3 or any(not math.isfinite(x) for x in a['position']):raise ValueError('Invalid position')
        if len(a['size'])!=3 or any(not math.isfinite(x) or x<=0 for x in a['size']):raise ValueError('Invalid prop size')
        if len(a['hints'])!=3 or not 1<=a['hint_delay']<=600:raise ValueError('Invalid hints')
        if not -100<=a['heat']<=100:raise ValueError('Invalid heat')
    visiting,done=set(),set(); byid={a['id']:a for a in actions}
    def walk(id):
        if id in visiting:raise ValueError('Dependency cycle: '+id)
        if id in done:return
        visiting.add(id)
        for dep in byid[id]['requires']+byid[id]['clues']+byid[id]['any_of']:walk(dep)
        visiting.remove(id);done.add(id)
    for id in ids:walk(id)
    quests=data['quests']+data['side_quests']; qids={q['id'] for q in quests}
    if len(qids)!=len(quests):raise ValueError('Duplicate quest')
    qdone=set(); qvis=set(); qs={q['id']:q for q in quests}
    def questwalk(id):
        if id in qvis:raise ValueError('Quest prerequisite cycle')
        if id in qdone:return
        qvis.add(id)
        for dep in qs[id]['requires']:questwalk(dep)
        qvis.remove(id);qdone.add(id)
    for q in quests:
        if not set(q['all']+q['any'])<=idset or not set(q['requires'])<=qids:raise ValueError('Unknown quest requirement')
    for id in qids:questwalk(id)
    for q in quests:
        for o in q['objectives']:
            if not o['type'] or not math.isfinite(o['amount']) or o['amount']<=0:raise ValueError('Invalid objective')
            targets=itemids if o['type']=='FindItem' else ({e['id'] for e in data['evidence_definitions']} if o['type']=='CollectEvidence' else idset)
            if o['type']!='SurviveTime' and o['target'] not in targets:raise ValueError('Unknown objective target')
    def s(v):return json.dumps(v,ensure_ascii=False)
    def ss(v):return '{'+','.join(map(s,v))+'}'
    def b(v):return 'true' if v else 'false'
    lines=['// Generated by Scripts/compile_chapter.py; edit Data/chapter1.json.','#pragma once','#include <string>','#include <vector>','namespace Wroclaw {',
    'struct ActionDef {std::string id,label,kind,body,answer,evidence,choice,alternate;std::vector<std::string> prerequisites,items,reward,clues,anyOf;float x,y,z;bool checkpoint;std::vector<std::string> tags,setTags,requireTags,consume,hints;bool safe,gate;float sx,sy,sz;std::string presentation,sound,doorState;double hintDelay,heat;};',
    'struct ObjectiveDefinition {std::string type,target;double amount=1;};',
    'struct QuestDef {std::string title;std::vector<std::string> all,any;std::string id,category,description,district;std::vector<std::string> prerequisites;int chapter;std::vector<ObjectiveDefinition> objectives;};',
    'struct ItemDef {std::string id,name,type;int stack;double weight;std::vector<std::string> tags;bool usable;};',
    'struct EvidenceDef {std::string id,category,validity;std::vector<std::string> persons,locations,events,requirements;};',
    'inline std::vector<ActionDef>& MutableCatalog(){static std::vector<ActionDef> Data={']
    for a in actions:
        fields=[s(a[k]) for k in ('id','label','kind','body','answer','evidence','choice','alternate')]+[ss(a[k]) for k in ('requires','items','reward','clues','any_of')]+[str(float(x))+'f' for x in a['position']]+[b(a['checkpoint'])]+[ss(a[k]) for k in ('tags','set_tags','require_tags','consume','hints')]+[b(a['safe']),b(a['gate'])]+[str(float(x))+'f' for x in a['size']]+[s(a[k]) for k in ('presentation','sound','door_state')]+[str(a['hint_delay']),str(a['heat'])]
        lines.append('{'+','.join(fields)+'},')
    lines+=['};return Data;}','inline const std::vector<ActionDef>& Catalog(){return MutableCatalog();}']
    for name,values in [('Quests',data['quests']),('SideQuests',data['side_quests'])]:
        lines+=['inline const std::vector<QuestDef>& '+name+'(){static const std::vector<QuestDef> Data={']
        for q in values:lines.append('{'+','.join([s(q['title']),ss(q['all']),ss(q['any'])]+[s(q[k]) for k in ('id','category','description','district')]+[ss(q['requires']),str(q['chapter']),'{'+','.join('{'+s(o['type'])+','+s(o['target'])+','+str(o['amount'])+'}' for o in q['objectives'])+'}'])+'},')
        lines+=['};return Data;}']
    lines+=['inline const std::vector<ItemDef>& Items(){static const std::vector<ItemDef> Data={']
    for i in data['items']:lines.append('{'+','.join([s(i[k]) for k in ('id','name','type')]+[str(i['stack']),str(i['weight']),ss(i['tags']),b(i['usable'])])+'},')
    lines+=['};return Data;}','inline const std::vector<EvidenceDef>& EvidenceDefinitions(){static const std::vector<EvidenceDef> Data={']
    for e in data['evidence_definitions']:lines.append('{'+','.join([s(e[k]) for k in ('id','category','validity')]+[ss(e[k]) for k in ('persons','locations','events','requirements')])+'},')
    lines+=['};return Data;}','inline const std::vector<std::string>& LightVariants(){static const std::vector<std::string> Data='+ss(data['variants'])+';return Data;}',
    'inline const std::string ChapterCompleteTag='+s(data['campaign']['chapter_complete_tag'])+';',
    'inline const std::vector<std::string> CampaignChapters='+ss(data['campaign']['required_chapters'])+';','}']
    return '\n'.join(lines)+'\n'
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    out=ROOT/'Source/WroclawTheGame/Content/ChapterCatalog.h';text=compile_catalog(json.loads((ROOT/'Data/chapter1.json').read_text()))
    if args.check:
        if not out.exists() or out.read_text()!=text:raise SystemExit('ChapterCatalog.h is stale')
    else:out.write_text(text,encoding='utf-8')
