"""Validate authoring data and emit the portable catalog used by UE and C++ tests."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def compile_catalog(data):
    actions = data['actions']
    ids = [a['id'] for a in actions]
    if len(ids) != len(set(ids)):
        raise ValueError('Duplicate action ID')
    allowed = {'read','pickup','virtual','use','code','password','door','choice','symbols','sequence','zone','lights','order','wires'}
    if len(set(data['variants'])) != len(data['variants']) or any(len(v)!=4 or set(v)!=set('1234') for v in data['variants']):
        raise ValueError('Light variants must be unique permutations of 1234')
    for a in actions:
        if a['kind'] not in allowed: raise ValueError('Unknown interaction kind')
        if a['alternate'] and a['alternate'] not in ids: raise ValueError('Unknown alternative')
        if a['answer'] and a['answer'] != '@variant' and not (1 <= len(a['answer']) <= 8): raise ValueError('Unsupported answer length')
        for key in ('requires', 'clues', 'any_of'):
            if not set(a[key]) <= set(ids):
                raise ValueError(f"Unknown references: {a['id']}/{key}")
        if len(a['position']) != 3:
            raise ValueError('Position must have three coordinates')
    visiting, done = set(), set()
    def walk(id):
        if id in visiting: raise ValueError(f'Dependency cycle: {id}')
        if id in done: return
        visiting.add(id)
        a = actions[ids.index(id)]
        for dep in a['requires'] + a['clues'] + a['any_of']: walk(dep)
        visiting.remove(id); done.add(id)
    for id in ids: walk(id)
    for q in data['quests']:
        if not set(q['all'] + q['any']) <= set(ids): raise ValueError('Unknown quest requirement')
    def string(s): return json.dumps(s, ensure_ascii=False)
    def strings(values): return '{' + ','.join(map(string, values)) + '}'
    lines = ['// Generated by Scripts/compile_chapter.py; edit Data/chapter1.json.', '#pragma once',
             '#include <string>', '#include <vector>', 'namespace Wroclaw {',
             'struct ActionDef {std::string id,label,kind,body,answer,evidence,choice,alternate; std::vector<std::string> prerequisites,items,reward,clues,anyOf; float x,y,z; bool checkpoint;};',
             'struct QuestDef {std::string title;std::vector<std::string> all,any;};',
             'inline const std::vector<ActionDef>& Catalog() { static const std::vector<ActionDef> Data = {']
    for a in actions:
        fields = [string(a[k]) for k in ('id','label','kind','body','answer','evidence','choice','alternate')]
        fields += [strings(a[k]) for k in ('requires','items','reward','clues','any_of')]
        fields += [str(float(x))+'f' for x in a['position']]
        fields += ['true' if a['checkpoint'] else 'false']
        lines.append(' {'+','.join(fields)+'},')
    lines += ['}; return Data; }', 'inline const std::vector<QuestDef>& Quests() { static const std::vector<QuestDef> Data = {']
    for q in data['quests']: lines.append(' {'+','.join([string(q['title']),strings(q['all']),strings(q['any'])])+'},')
    lines += ['}; return Data; }','inline const std::vector<std::string>& LightVariants() {static const std::vector<std::string> Data = '+strings(data['variants'])+'; return Data;}','}']
    return '\n'.join(lines)+'\n'

if __name__ == '__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    output=ROOT/'Source/WroclawTheGame/Content/ChapterCatalog.h'
    text=compile_catalog(json.loads((ROOT/'Data/chapter1.json').read_text(encoding='utf-8')))
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != text: raise SystemExit('ChapterCatalog.h is stale; run Scripts/compile_chapter.py')
    else: output.write_text(text,encoding='utf-8')
