// Generated by Scripts/compile_world.py; edit Data/openworld.json.
#pragma once
#include <string>
#include <vector>
namespace Wroclaw {
struct NPCDef {std::string id;std::string name;std::string faction;std::string role;std::string dialogue;std::vector<double> position;std::vector<double> hours;std::vector<std::vector<double>> destinations;};
inline const std::vector<NPCDef>& NPCs(){static const std::vector<NPCDef> data={
{"informant","Mieszkaniec skweru","residents","Informant","O zmroku unikaj kamery przy skwerze. Skrzynka C-3 jest na wschodniej ścianie.",{11600,7000,96},{0,8,18},{{14300,7600,96},{11500,7000,96},{11600,7000,96}}},
};return data;}
struct DistrictDef {std::string id;std::string name;std::vector<double> bounds;double threat;std::string ambient;double light;std::vector<std::string> tags;std::vector<std::string> activities;std::vector<std::string> events;std::vector<std::string> safehouses;std::vector<std::string> enemies;};
inline const std::vector<DistrictDef>& Districts(){static const std::vector<DistrictDef> data={
{"apartment","Kamienica",{0,0,-400,4400,1200,1400},0,"Apartment",0.7,{"District.Apartment"},{},{},{},{}},
{"nadodrze","Nadodrze",{1700,1200,-400,15800,9300,1800},1,"Street",0.8,{"District.Nadodrze"},{},{},{},{}},
};return data;}
struct GuardDef {std::string id;std::string profile;std::string faction;std::string district;std::vector<double> position;std::vector<std::vector<double>> patrol;std::vector<std::string> prerequisites;std::vector<std::string> tags;double sight;double hearing;double walk;double chase;double health;double radio_delay;double radio_range;double full_range;double simple_range;};
inline const std::vector<GuardDef>& Guards(){static const std::vector<GuardDef> data={
{"hall","assassin","hunters","apartment",{2180,620,96},{{2180,620,96},{1940,400,136},{2200,800,96}},{"target"},{"Enemy.Assassin"},1800,1700,210,400,100,3,2200,3500,6500},
{"courtyard","assassin","hunters","nadodrze",{3200,1850,96},{{2900,1950,96},{4100,1480,96},{3700,2040,96}},{"apartment_exit"},{"Enemy.Assassin"},1800,1700,210,400,100,3,2200,3500,6500},
{"pursuer","assassin","hunters","nadodrze",{7300,2900,96},{{7300,2900,96},{7800,3000,96}},{"usb"},{"Enemy.Assassin"},1800,1700,210,400,100,3,2200,3500,6500},
{"park_patrol","assassin","hunters","nadodrze",{10900,6900,96},{{10900,6900,96},{12300,7000,96},{11700,4700,96},{9800,2800,96}},{},{"Enemy.Assassin"},1800,1700,210,400,100,3,2200,3500,6500},
};return data;}
struct LocationDef {std::string id;std::string name;std::vector<double> position;double radius;std::string action;bool safehouse;};
inline const std::vector<LocationDef>& Locations(){static const std::vector<LocationDef> data={
{"shop","Sklep",{5300,1500,100},700,"",false},
{"park","Skwer",{11500,6000,100},1200,"",false},
{"workshop","Stary warsztat",{10600,5500,100},700,"",false},
{"park_shelter","Schronienie przy skwerze",{14500,7500,100},700,"safehouse_rest",true},
{"hidden","Ukryta pracownia",{13300,8500,100},550,"",false},
};return data;}
struct WorldEventDef {std::string id;std::string name;std::string type;std::string district;std::vector<double> position;double chance;double min_heat;double max_heat;double start_hour;double end_hour;std::vector<std::string> weathers;std::vector<std::string> prerequisites;std::vector<std::string> require_tags;double cooldown;bool hostile;std::string action;double noise;double heat;};
inline const std::vector<WorldEventDef>& WorldEvents(){static const std::vector<WorldEventDef> data={
{"shot","Z bocznej ulicy słychać trzask. Ktoś ucieka za kamienicę.","EnvironmentalEvent","nadodrze",{9000,7600,100},0.5,0,100,0,24,{"Clear","Cloudy","Rain","Fog","Storm"},{},{},120,false,"",1500,0},
{"observer","Ten sam zaparkowany samochód. Silnik nadal pracuje.","SuspiciousVehicle","nadodrze",{13500,2900,100},0.65,0,100,0,24,{"Clear","Cloudy","Rain","Fog","Storm"},{},{},120,false,"",0,0},
{"neighbor_call","Sąsiad dziękuje za pomoc: przy skwerze można odpocząć.","PhoneCall","nadodrze",{10000,3000,100},0.5,0,100,0,24,{"Clear","Cloudy","Rain","Fog","Storm"},{},{"NPC.Neighbor.Saved"},600,false,"",0,0},
{"cache","Ktoś zostawił paczkę przy ławce. Warto zbadać skwer.","HiddenCache","nadodrze",{11800,7100,100},0.35,0,100,0,24,{"Clear","Cloudy","Rain","Fog","Storm"},{},{},120,false,"",0,0},
{"search","Słyszysz wezwanie patrolu. Zostań poza światłem.","EnemyPatrol","nadodrze",{11300,6900,100},0.5,30,100,0,24,{"Clear","Cloudy","Rain","Fog","Storm"},{},{},180,true,"",1800,3},
};return data;}
struct HideDef {std::string id;std::string name;std::vector<double> position;std::vector<double> exit;double radius;};
inline const std::vector<HideDef>& Hides(){static const std::vector<HideDef> data={
{"container","Kontener na podwórku",{3300,1750,100},{3410,1750,100},180},
{"park_hiding","Ciemna wnęka przy skwerze",{11400,7850,100},{11300,7850,100},180},
{"garage_hiding","Miejsce za regałem",{9250,4290,100},{9270,4410,100},180},
};return data;}
struct CCTVDef {std::string id;std::vector<double> position;std::vector<double> rotation;double radius;std::string disabled_tag;std::string power_tag;double alarm_heat;};
inline const std::vector<CCTVDef>& Cameras(){static const std::vector<CCTVDef> data={
{"park_camera",{12000,5900,340},{-12,90,0},1500,"Power.Park.Disabled","",15},
};return data;}
struct WeatherDef {std::string id;double visibility;double noise;double fog;};
inline const std::vector<WeatherDef>& WeatherProfiles(){static const std::vector<WeatherDef> data={
{"Clear",1,1,0.008},
{"Cloudy",0.85,1,0.012},
{"Rain",0.65,0.75,0.025},
{"Fog",0.4,0.9,0.07},
{"Storm",0.5,0.55,0.04},
};return data;}
struct FactionDef {std::string a;std::string b;std::string relation;};
inline const std::vector<FactionDef>& Factions(){static const std::vector<FactionDef> data={
{"player","hunters","Hostile"},
{"player","residents","Neutral"},
{"hunters","residents","Suspicious"},
};return data;}
struct MessageDef {std::string id;std::string sender;std::string text;std::vector<std::string> prerequisites;std::vector<std::string> tags;double min_heat;};
inline const std::vector<MessageDef>& Messages(){static const std::vector<MessageDef> data={
{"intro","M.","Nie ufaj głównemu wejściu.",{"sms"},{},0},
{"thanks","Sąsiad","Przy skwerze jest schronienie. Dziękuję za pomoc.",{},{"NPC.Neighbor.Saved"},0},
{"heat_warning","M.","Patrole cię szukają. Zejdź ze światła i zgub kontakt.",{"street"},{},50},
};return data;}
struct PhoneAppDef {std::string id;std::string title;std::string text;std::vector<std::string> on_open;};
inline const std::vector<PhoneAppDef>& PhoneApps(){static const std::vector<PhoneAppDef> data={
{"messages","Wiadomości","",{"sms"}},
{"calls","Połączenia","Ostatnie połączenie: 02:17. Numer zastrzeżony.",{"contact"}},
{"contacts","Kontakty","M. — numer zastrzeżony. Nadawca ostrzegł przed wejściem.",{"contact"}},
{"camera","Aparat","C — zapisz opis fotografii obserwowanej wskazówki.",{}},
{"gallery","Galeria","",{}},
{"map","Mapa odkryć","",{}},
{"notes","Notatki","",{}},
{"investigation","Śledztwo","",{}},
{"objectives","Cele","",{}},
};return data;}
struct NoiseDef {std::string id;double radius;double intensity;double heat;};
inline const std::vector<NoiseDef>& NoiseProfiles(){static const std::vector<NoiseDef> data={
{"Walk",650,0.35,0},
{"Sprint",1700,1,0},
{"Crouch",200,0.12,0},
{"Door",700,0.5,0},
{"Glass",2200,1,5},
{"Combat",1600,1,5},
{"Throw",2400,1.2,0},
{"Alarm",2400,1.5,10},
};return data;}
struct CombinationDef {std::string id;std::string title;std::vector<std::string> evidence;std::string action;};
inline const std::vector<CombinationDef>& Combinations(){static const std::vector<CombinationDef> data={
{"vehicle","Samochód + monitoring + radio",{"car_document","cctv","radio_recording"},"combine_vehicle"},
};return data;}
inline constexpr double clock_rate=6;
inline constexpr double initial_hour=19;
inline constexpr double quiet_seconds=35;
inline constexpr double event_interval=18;
inline constexpr double heat_decay=0.12;
inline const std::string initial_weather="Cloudy";
}
